version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_development
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  rails_app:
    build: ./recycling_rails
    entrypoint: ./entrypoint.sh
    command: "rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./recycling_rails:/app
    ports:
      - "8080:8080"
    image: recycling_rails:latest
    container_name: recycling_rails
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      DB_USER: dbuser
      DB_NAME: db_development
      DB_PASSWORD: password
      DB_HOST: db

    stdin_open: true 
    tty: true
  react_app:
    build: ./recycling_react
    volumes:
      - ./recycling_react:/app
      - exclude:/app/node_modules 
    ports:
      - "3000:3000"
    image: recycling_react:latest
    container_name: recycling_react
    command: ./entrypoint.sh
      
volumes: 
  exclude: 
  mysqldata:
